version: '2'
services:
  db:
    build: ./api/database_image
  api:
    build: ./api
    command: rails s -p 8888 -b 0.0.0.0
    ports:
      - "8888:8888"
    depends_on:
      - db
  client:
    build: ./client
    command: npm run start:prod
    ports:
      - "3000:3000"
    depends_on:
      - api
