default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost

development:
  <<: *default
  database: info_messages_development

test:
  <<: *default
  database: info_messages_test

production:
  <<: *default
  database: postgres
  username: postgres
  host: db
  password:
